### ISSUE TITLE
Fig 11 board and schematics discrepancies

### ISSUE THREAD

**Issue by amchagas** [BadenLab/DBOscope#2]
Figure 11 C contains schematics for ETL driver board. 
On top left of panel, we see an input and a Zener diode:
1- There is no label on what that input is
2 - The panels showing the rendering of the board contains no zener diode. 

Please see #1 for a more complete version of the board. Let me know if there should be a Zener diode in the board, and what are the specs so I can add it to #1

**Comment by filipjaniak** [comment]
Ok, Zener diode is there as additional protection for unstable Arduino (we have a series of them working very strange), and it is in use as a connector between Arduino and  ETL driver. Manual text is corrected.

**Comment by amchagas** [comment]
Great, thanks for the review! closing this issue.
